networks:
    WebMMP:
        driver: bridge
services:
    app:
        container_name: mathmechmaps
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "80:80"
        networks:
            - WebMMP
        depends_on:
            - postgres_db
    postgres_db:
        container_name: postgres_db
        image: postgres
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: password123
            POSTGRES_DB: mathmechmaps
        ports:
            - "5432:5432"
        networks:
            - WebMMP
        volumes:
            - postgres-data:/var/lib/postgresql/data
volumes:
    postgres-data: