public static class AuditoryBook
{
    public static Dictionary<string, BookTypes> Book = new Dictionary<string, BookTypes>() {
            {"500", BookTypes.free},
            {"501", BookTypes.free},
            {"502", BookTypes.free},
            {"503", BookTypes.free},
            {"504", BookTypes.free},
            {"505", BookTypes.free},
            {"506", BookTypes.free},
            {"507", BookTypes.free},
            {"508", BookTypes.free},
            {"509", BookTypes.free},
            {"510", BookTypes.free},
            {"511", BookTypes.free},
            {"512", BookTypes.free},
            {"513", BookTypes.free},
            {"514", BookTypes.free},
            {"515", BookTypes.free},
            {"516", BookTypes.free},
            {"517", BookTypes.free},
            {"518", BookTypes.free},
            {"519", BookTypes.free},
            {"520", BookTypes.free},
            {"521", BookTypes.free},
            {"522", BookTypes.free},
            {"523", BookTypes.free},
            {"524", BookTypes.free},
            {"524a", BookTypes.free},
            {"525", BookTypes.free},
            {"526", BookTypes.free},
            {"527", BookTypes.free},
            {"528", BookTypes.free},
            {"529", BookTypes.free},
            {"530", BookTypes.free},
            {"531", BookTypes.free},
            {"532", BookTypes.free},
            {"533", BookTypes.free},
            {"534", BookTypes.free},
            {"535", BookTypes.free},
            {"536", BookTypes.free},
            {"537", BookTypes.free},
            {"538", BookTypes.free},
            {"539", BookTypes.free},
            {"540", BookTypes.free},
            {"541", BookTypes.free},
            {"542", BookTypes.free},
            {"543", BookTypes.free},
            {"544", BookTypes.free},
            {"545", BookTypes.free},
            {"546", BookTypes.free},
            {"547", BookTypes.free},
            {"548", BookTypes.free},
            {"549", BookTypes.free},
            {"550", BookTypes.free},
            {"551", BookTypes.free},
            {"552", BookTypes.free},
            {"553", BookTypes.free},
            {"554", BookTypes.free},
            {"555", BookTypes.free},
            {"556", BookTypes.free},
            {"557", BookTypes.free},
            {"558", BookTypes.free},
            {"559", BookTypes.free},
            {"560", BookTypes.free},
            {"561", BookTypes.free},
            {"562", BookTypes.free},
            {"563", BookTypes.free},
            {"564", BookTypes.free},
            {"565", BookTypes.free},
            {"600", BookTypes.free},
            {"601", BookTypes.free},
            {"602", BookTypes.free},
            {"603", BookTypes.free},
            {"604", BookTypes.free},
            {"605", BookTypes.free},
            {"606", BookTypes.free},
            {"607", BookTypes.free},
            {"608", BookTypes.free},
            {"609", BookTypes.free},
            {"610", BookTypes.free},
            {"611", BookTypes.free},
            {"612", BookTypes.free},
            {"613", BookTypes.free},
            {"614", BookTypes.free},
            {"615", BookTypes.free},
            {"616", BookTypes.free},
            {"617", BookTypes.free},
            {"618", BookTypes.free},
            {"619", BookTypes.free},
            {"620", BookTypes.free},
            {"621", BookTypes.free},
            {"622", BookTypes.free},
            {"622a", BookTypes.free},
            {"623", BookTypes.free},
            {"624", BookTypes.free},
            {"625", BookTypes.free},
            {"626", BookTypes.free},
            {"627", BookTypes.free},
            {"628", BookTypes.free},
            {"629", BookTypes.free},
            {"630", BookTypes.free},
            {"631", BookTypes.free},
            {"632", BookTypes.free},
            {"632a", BookTypes.free},
            {"633", BookTypes.free},
            {"634", BookTypes.free},
            {"635", BookTypes.free},
            {"636", BookTypes.free},
            {"637", BookTypes.free},
            {"638", BookTypes.free},
            {"639", BookTypes.free},
            {"640", BookTypes.free},
            {"641", BookTypes.free},
            {"642", BookTypes.free},
            {"643", BookTypes.free},
            {"644", BookTypes.free},
            {"645", BookTypes.free},
            {"646", BookTypes.free},
            {"647", BookTypes.free},
            {"648", BookTypes.free},
            {"649", BookTypes.free},
            {"650", BookTypes.free},
            {"651", BookTypes.free},
            {"652", BookTypes.free},
            {"653", BookTypes.free},
            {"654", BookTypes.free},
            {"655", BookTypes.free},
            {"656", BookTypes.free},
            {"657", BookTypes.free},
            {"658", BookTypes.free},
            {"659", BookTypes.free},
            {"660", BookTypes.free},
            {"661", BookTypes.free},
            {"662", BookTypes.free},
            {"663", BookTypes.free},
            {"664", BookTypes.free},
            {"665", BookTypes.free}
        };

    public static Dictionary<string, string> BookIp = new Dictionary<string, string>();

    public static void ClearBook()
    {
        foreach (var key in Book.Keys)
        {
            Book[key] = BookTypes.free;
        }
    }
}